export const genres = [
  {
    id: 28,
    name: "Action",
  },
  {
    id: 12,
    name: "Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 14,
    name: "Fantasy",
  },
  {
    id: 36,
    name: "History",
  },
  {
    id: 27,
    name: "Horror",
  },
  {
    id: 10402,
    name: "Music",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10749,
    name: "Romance",
  },
  {
    id: 878,
    name: "Science Fiction",
  },
  {
    id: 10770,
    name: "TV Movie",
  },
  {
    id: 53,
    name: "Thriller",
  },
  {
    id: 10752,
    name: "War",
  },
  {
    id: 37,
    name: "Western",
  },
];

export const movies = [
  {
    adult: false,
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    popularity: 5464.692,
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    release_date: "2024-07-24",
    title: "Deadpool & Wolverine",
    video: false,
    vote_average: 7.763,
    vote_count: 2422,
  },
  {
    adult: false,
    backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 1022789,
    original_language: "en",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    popularity: 2641.2,
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    release_date: "2024-06-11",
    title: "Inside Out 2",
    video: false,
    vote_average: 7.68,
    vote_count: 3040,
  },
  {
    adult: false,
    backdrop_path: "/3q01ACG0MWm0DekhvkPFCXyPZSu.jpg",
    genre_ids: [28, 80, 53, 35],
    id: 573435,
    original_language: "en",
    original_title: "Bad Boys: Ride or Die",
    overview:
      "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
    popularity: 1751.057,
    poster_path: "/oGythE98MYleE6mZlGs5oBGkux1.jpg",
    release_date: "2024-06-05",
    title: "Bad Boys: Ride or Die",
    video: false,
    vote_average: 7.571,
    vote_count: 1728,
  },
  {
    adult: false,
    backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
    genre_ids: [16, 10751, 35, 28],
    id: 519182,
    original_language: "en",
    original_title: "Despicable Me 4",
    overview:
      "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    popularity: 2051.558,
    poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    release_date: "2024-06-20",
    title: "Despicable Me 4",
    video: false,
    vote_average: 7.262,
    vote_count: 1263,
  },
  {
    adult: false,
    backdrop_path: "/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg",
    genre_ids: [28, 12, 18, 53],
    id: 718821,
    original_language: "en",
    original_title: "Twisters",
    overview:
      "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
    popularity: 2017.748,
    poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
    release_date: "2024-07-10",
    title: "Twisters",
    video: false,
    vote_average: 7.026,
    vote_count: 1094,
  },
  {
    adult: false,
    backdrop_path: "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
    genre_ids: [28, 80],
    id: 1160018,
    original_language: "hi",
    original_title: "Kill",
    overview:
      "When an army commando finds out his true love is engaged against her will, he boards a New Dehli-bound train in a daring quest to derail the arranged marriage. But when a gang of knife-wielding thieves begin to terrorize innocent passengers on his train, the commando takes them on himself in a death-defying kill-spree to save those around him — turning what should have been a typical commute into an adrenaline-fueled thrill ride.",
    popularity: 1386.744,
    poster_path: "/m2zXTuNPkywdYLyWlVyJZW2QOJH.jpg",
    release_date: "2024-07-03",
    title: "Kill",
    video: false,
    vote_average: 6.825,
    vote_count: 103,
  },
  {
    adult: false,
    backdrop_path: "/pzFbYJfqGKlGxOsDIIsUi6YxVQ.jpg",
    genre_ids: [28, 35, 878],
    id: 1094138,
    original_language: "en",
    original_title: "Jackpot!",
    overview:
      "In the near future, a 'Grand Lottery' has been established - the catch: kill the winner before sundown to legally claim their multi-billion dollar jackpot. When Katie Kim mistakenly finds herself with the winning ticket, she reluctantly joins forces with amateur lottery protection agent Noel Cassidy who must get her to sundown in exchange for a piece of her prize.",
    popularity: 1419.609,
    poster_path: "/fOsamTFIyGxjw1jLSKdZYxQBJOT.jpg",
    release_date: "2024-08-13",
    title: "Jackpot!",
    video: false,
    vote_average: 6.403,
    vote_count: 319,
  },
  {
    adult: false,
    backdrop_path: "/4ft6TR9wA6bra0RLL6G7JFDQ5t1.jpg",
    genre_ids: [28, 35],
    id: 704239,
    original_language: "en",
    original_title: "The Union",
    overview:
      "A New Jersey construction worker goes from regular guy to aspiring spy when his long-lost high school sweetheart recruits him for an espionage mission.",
    popularity: 1686.712,
    poster_path: "/d9CTnTHip1RbVi2OQbA2LJJQAGI.jpg",
    release_date: "2024-08-15",
    title: "The Union",
    video: false,
    vote_average: 6.275,
    vote_count: 402,
  },
  {
    adult: false,
    backdrop_path: "/bxwKC4qAbceMgHU1xCCTBK1eYdn.jpg",
    genre_ids: [28, 53, 80],
    id: 5492,
    original_language: "en",
    original_title: "Gunner",
    overview:
      "While on a camping trip in order to reconnect, war veteran Colonel Lee Gunner must save his two sons from a gang of violent bikers when they're kidnapped after accidentally stumbling upon to a massive drug operation.",
    popularity: 1603.424,
    poster_path: "/eEkAY5veAnwxUOOlpF62KawkFO9.jpg",
    release_date: "2024-08-16",
    title: "Gunner",
    video: false,
    vote_average: 5.133,
    vote_count: 45,
  },
  {
    adult: false,
    backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
    genre_ids: [10749, 18],
    id: 1079091,
    original_language: "en",
    original_title: "It Ends with Us",
    overview:
      "When a woman's first love suddenly reenters her life, her relationship with a charming, but abusive neurosurgeon is upended, and she realizes she must learn to rely on her own strength to make an impossible choice for her future.",
    popularity: 1540.276,
    poster_path: "/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg",
    release_date: "2024-08-07",
    title: "It Ends with Us",
    video: false,
    vote_average: 6.931,
    vote_count: 189,
  },
  {
    adult: false,
    backdrop_path: "/rSRA1p4e3laAAJflzdgtqNlx27Y.jpg",
    genre_ids: [28],
    id: 1049574,
    original_language: "en",
    original_title: "Darkness of Man",
    overview:
      "Russell Hatch, an Interpol operative who takes on the role of father figure to Jayden, the son of an informant killed in a routine raid gone wrong. Years later, Hatch finds himself protecting Jayden and his grandfather from a group of merciless gangs in an all-out turf war, stopping at nothing to protect Jayden and fight anyone getting in his way.",
    popularity: 1395.126,
    poster_path: "/fzmQ7mMYlBE8q459F6x9BAGgmj9.jpg",
    release_date: "2024-05-07",
    title: "Darkness of Man",
    video: false,
    vote_average: 6.5,
    vote_count: 100,
  },
  {
    adult: false,
    backdrop_path: "/n3JeGELHa9V6k9mL81ItMxWLSS6.jpg",
    genre_ids: [28, 53],
    id: 1129598,
    original_language: "en",
    original_title: "Prey",
    overview:
      "A young couple is compelled to leave their Christian missionary station in the Kalahari Desert after being threatened with death by an extremist militant gang. After crashing their aircraft they must battle man and beast for their lives.",
    popularity: 966.674,
    poster_path: "/5wAlO5zZ3IyzLBAf7cp5WejalmG.jpg",
    release_date: "2024-03-15",
    title: "Prey",
    video: false,
    vote_average: 6.472,
    vote_count: 198,
  },
  {
    adult: false,
    backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    genre_ids: [27, 878],
    id: 945961,
    original_language: "en",
    original_title: "Alien: Romulus",
    overview:
      "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    popularity: 1237.577,
    poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    release_date: "2024-08-13",
    title: "Alien: Romulus",
    video: false,
    vote_average: 7.215,
    vote_count: 657,
  },
  {
    adult: false,
    backdrop_path: "/hdFIdXwS8FSN2wIsuotjW1mshI0.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 831815,
    original_language: "en",
    original_title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
    overview:
      "When Bikini Bottom is scooped from the ocean, scientific squirrel Sandy Cheeks and her pal SpongeBob SquarePants saddle up for Texas to save their town.",
    popularity: 910.391,
    poster_path: "/30YnfZdMNIV7noWLdvmcJS0cbnQ.jpg",
    release_date: "2024-08-01",
    title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
    video: false,
    vote_average: 6.37,
    vote_count: 181,
  },
  {
    adult: false,
    backdrop_path: "/6XjMwQTvnICBz6TguiDKkDVHvgS.jpg",
    genre_ids: [27, 878, 53],
    id: 762441,
    original_language: "en",
    original_title: "A Quiet Place: Day One",
    overview:
      "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
    popularity: 1179.988,
    poster_path: "/hU42CRk14JuPEdqZG3AWmagiPAP.jpg",
    release_date: "2024-06-26",
    title: "A Quiet Place: Day One",
    video: false,
    vote_average: 6.865,
    vote_count: 1502,
  },
  {
    adult: false,
    backdrop_path: "/aswBReNN2adqTiOBnvh96RCDeJP.jpg",
    genre_ids: [28, 80, 18],
    id: 959092,
    original_language: "fr",
    original_title: "Farang",
    overview:
      "Sam is a professional boxer about to get released from prison. While on parole, his past catches up with him and he has no choice but to flee. Five years later, he has rebuilt a simple life on an exotic island in Thailand with his wife and her daughter, but when he gets blackmailed by a dangerous local godfather, he must embark on a dangerous drug smuggling mission which results in a tragedy. Now has only one purpose: to seek merciless vengeance.",
    popularity: 882.732,
    poster_path: "/u9035lysUz3ccloQt0SeIp1Mu8a.jpg",
    release_date: "2023-06-28",
    title: "Mayhem!",
    video: false,
    vote_average: 6.677,
    vote_count: 141,
  },
  {
    adult: false,
    backdrop_path: "/h9YlRHAZWOWtGonllmj6JJg1FrE.jpg",
    genre_ids: [28, 12, 16, 10751, 14],
    id: 588648,
    original_language: "zh",
    original_title: "Dragonkeeper",
    overview:
      "Set in Han Imperial China, the plot follows the adventures of enslaved girl Ping with ancient dragon Long Danzi. Dragons had been banished from the kingdom. Ping, an orphan, finds one of the last remaining dragon eggs. Palace guards force Ping to run away in order to return the dragon egg to the ocean and save all dragons from extinction. Ping discovers that she is a true Dragonkeeper.",
    popularity: 813.156,
    poster_path: "/ggZGnJLzO3BTu7ysuuIzou3Oex5.jpg",
    release_date: "2024-04-11",
    title: "Dragonkeeper",
    video: false,
    vote_average: 7.056,
    vote_count: 63,
  },
  {
    adult: false,
    backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
    genre_ids: [878, 12, 28],
    id: 653346,
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview:
      "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
    popularity: 825.523,
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    release_date: "2024-05-08",
    title: "Kingdom of the Planet of the Apes",
    video: false,
    vote_average: 7.141,
    vote_count: 2645,
  },
  {
    adult: false,
    backdrop_path: "/9msuazXGWAyl7vhxVFU7e7Bb5Ik.jpg",
    genre_ids: [18, 10749],
    id: 179387,
    original_language: "tl",
    original_title: "Heavenly Touch",
    overview:
      "Jonard is having trouble making ends meet. His mother is suffering from depression, and he and his sister are forced to quit school in order to take care of her. One day, Jonard meets up his friend Rodel, and Rodel introduces him to the world of massage parlors. Rodel teaches him massage, and brings him to Heavenly Touch, a syndicate-run massage parlor that mostly caters to homosexuals.",
    popularity: 639.847,
    poster_path: "/ory8WuAqznTE7lfopTSymHpop2t.jpg",
    release_date: "2009-05-12",
    title: "Heavenly Touch",
    video: false,
    vote_average: 6.2,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: "/1wP1phHo2CROOqzv7Azs0MT5esU.jpg",
    genre_ids: [16, 35, 10751, 12, 28],
    id: 748783,
    original_language: "en",
    original_title: "The Garfield Movie",
    overview:
      "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
    popularity: 865.778,
    poster_path: "/xYduFGuch9OwbCOEUiamml18ZoB.jpg",
    release_date: "2024-04-30",
    title: "The Garfield Movie",
    video: false,
    vote_average: 7.152,
    vote_count: 837,
  },
];

export const cast = [
  {
    adult: false,
    gender: 2,
    id: 10859,
    known_for_department: "Acting",
    name: "Ryan Reynolds",
    original_name: "Ryan Reynolds",
    popularity: 85.732,
    profile_path: "/2Orm6l3z3zukF1q0AgIOUqvwLeB.jpg",
    cast_id: 252,
    character: "Wade Wilson / Deadpool / Nicepool",
    credit_id: "66a0eeb7fadd7c4c9c38207f",
    order: 0,
  },
  {
    adult: false,
    gender: 2,
    id: 6968,
    known_for_department: "Acting",
    name: "Hugh Jackman",
    original_name: "Hugh Jackman",
    popularity: 66.869,
    profile_path: "/4Xujtewxqt6aU0Y81tsS9gkjizk.jpg",
    cast_id: 253,
    character: "Logan / Wolverine",
    credit_id: "66a0eef54192f70fea09dc90",
    order: 1,
  },
  {
    adult: false,
    gender: 3,
    id: 2324569,
    known_for_department: "Acting",
    name: "Emma Corrin",
    original_name: "Emma Corrin",
    popularity: 51.066,
    profile_path: "/wqGOVOsHzZaHeHymIS40elGCnY0.jpg",
    cast_id: 254,
    character: "Cassandra Nova",
    credit_id: "66a0ef1ca5ab9d9f3d705ed1",
    order: 2,
  },
  {
    adult: false,
    gender: 2,
    id: 15576,
    known_for_department: "Acting",
    name: "Matthew Macfadyen",
    original_name: "Matthew Macfadyen",
    popularity: 29.181,
    profile_path: "/2FF3Yjxd7DYR4EIJL6s2GpKDMkJ.jpg",
    cast_id: 256,
    character: "Mr. Paradox",
    credit_id: "66a0ef54aab1abca4f09e107",
    order: 3,
  },
  {
    adult: false,
    gender: 1,
    id: 1464650,
    known_for_department: "Acting",
    name: "Dafne Keen",
    original_name: "Dafne Keen",
    popularity: 41.378,
    profile_path: "/g325OIjIHrFr0te8ewPfhKQ2SKj.jpg",
    cast_id: 271,
    character: "Laura / X-23",
    credit_id: "66a0f13d76eb26a1ca381cc0",
    order: 4,
  },
  {
    adult: false,
    gender: 2,
    id: 15277,
    known_for_department: "Acting",
    name: "Jon Favreau",
    original_name: "Jon Favreau",
    popularity: 20.434,
    profile_path: "/tnx7iMVydPQXGOoLsxXl84PXtbA.jpg",
    cast_id: 278,
    character: "Happy Hogan",
    credit_id: "66a0f232a9212776c5e0d638",
    order: 5,
  },
  {
    adult: false,
    gender: 1,
    id: 54882,
    known_for_department: "Acting",
    name: "Morena Baccarin",
    original_name: "Morena Baccarin",
    popularity: 77.721,
    profile_path: "/kBSKKaOtsqIzZPhtEeHfCBmhWl9.jpg",
    cast_id: 255,
    character: "Vanessa",
    credit_id: "66a0ef353e68414965705f0c",
    order: 6,
  },
  {
    adult: false,
    gender: 2,
    id: 1091324,
    known_for_department: "Acting",
    name: "Rob Delaney",
    original_name: "Rob Delaney",
    popularity: 11.226,
    profile_path: "/xirfT1znRkkughLiPemKu3NhkKQ.jpg",
    cast_id: 261,
    character: "Peter",
    credit_id: "66a0f01b537cac04b109e17e",
    order: 7,
  },
  {
    adult: false,
    gender: 1,
    id: 122750,
    known_for_department: "Acting",
    name: "Leslie Uggams",
    original_name: "Leslie Uggams",
    popularity: 26.807,
    profile_path: "/peLaqLcs3y2WY4TbrLOXQGt9I8S.jpg",
    cast_id: 259,
    character: "Blind Al",
    credit_id: "66a0efdb073923ad4918be52",
    order: 8,
  },
  {
    adult: false,
    gender: 1,
    id: 9278,
    known_for_department: "Acting",
    name: "Jennifer Garner",
    original_name: "Jennifer Garner",
    popularity: 52.737,
    profile_path: "/ftymEXqdTnXfaI6dGd9qrJoFOSE.jpg",
    cast_id: 258,
    character: "Elektra",
    credit_id: "66a0efbef3ce01f00535f865",
    order: 9,
  },
  {
    adult: false,
    gender: 2,
    id: 10814,
    known_for_department: "Acting",
    name: "Wesley Snipes",
    original_name: "Wesley Snipes",
    popularity: 36.106,
    profile_path: "/81D6oJ81kiQ5xnEHhaHrY29ntdO.jpg",
    cast_id: 272,
    character: "Blade",
    credit_id: "66a0f1546aef695b11dd76e5",
    order: 10,
  },
  {
    adult: false,
    gender: 2,
    id: 38673,
    known_for_department: "Acting",
    name: "Channing Tatum",
    original_name: "Channing Tatum",
    popularity: 89.73,
    profile_path: "/e5p1xrGtPfpJBQR9Pt3B6W4buZP.jpg",
    cast_id: 274,
    character: "Gambit",
    credit_id: "66a0f19973c78cc0c05dadf0",
    order: 11,
  },
  {
    adult: false,
    gender: 2,
    id: 16828,
    known_for_department: "Acting",
    name: "Chris Evans",
    original_name: "Chris Evans",
    popularity: 47.565,
    profile_path: "/3bOGNsHlrswhyW79uvIHH1V43JI.jpg",
    cast_id: 288,
    character: "Johnny Storm",
    credit_id: "66a10565ceae5015037060b3",
    order: 12,
  },
  {
    adult: false,
    gender: 2,
    id: 73968,
    known_for_department: "Acting",
    name: "Henry Cavill",
    original_name: "Henry Cavill",
    popularity: 81.802,
    profile_path: "/iWdKjMry5Pt7vmxU7bmOQsIUyHa.jpg",
    cast_id: 280,
    character: "The Cavillrine",
    credit_id: "66a0f26fbffb534f84e0d621",
    order: 13,
  },
  {
    adult: false,
    gender: 1,
    id: 134774,
    known_for_department: "Acting",
    name: "Wunmi Mosaku",
    original_name: "Wunmi Mosaku",
    popularity: 17.518,
    profile_path: "/mWDsVCo9sBcekrsjUTsoCFLhtYt.jpg",
    cast_id: 277,
    character: "B-15",
    credit_id: "66a0f20f1e7b0e8bf5dd7752",
    order: 14,
  },
  {
    adult: false,
    gender: 2,
    id: 11022,
    known_for_department: "Acting",
    name: "Aaron Stanford",
    original_name: "Aaron Stanford",
    popularity: 11.922,
    profile_path: "/xt2c0vdTb6UmSFq6fl09iCcIFve.jpg",
    cast_id: 265,
    character: "Pyro",
    credit_id: "66a0f09a3631af76bb09dac3",
    order: 15,
  },
  {
    adult: false,
    gender: 2,
    id: 9832,
    known_for_department: "Acting",
    name: "Tyler Mane",
    original_name: "Tyler Mane",
    popularity: 11.1,
    profile_path: "/h5knoBWStVv7a0FKPwfKV7f7Ez1.jpg",
    cast_id: 266,
    character: "Sabretooth",
    credit_id: "66a0f0b53eaae4a1e3bf6473",
    order: 16,
  },
  {
    adult: false,
    gender: 2,
    id: 1109702,
    known_for_department: "Acting",
    name: "Karan Soni",
    original_name: "Karan Soni",
    popularity: 15.117,
    profile_path: "/t3eNrzRKy3wTVCUiEp002UXbjxX.jpg",
    cast_id: 263,
    character: "Dopinder",
    credit_id: "66a0f06295bbae847e381c4f",
    order: 17,
  },
  {
    adult: false,
    gender: 1,
    id: 1492326,
    known_for_department: "Acting",
    name: "Brianna Hildebrand",
    original_name: "Brianna Hildebrand",
    popularity: 17.417,
    profile_path: "/8lGwV4rMQReWMlsXhLBYMRTYzTA.jpg",
    cast_id: 257,
    character: "Negasonic Teenage Warhead",
    credit_id: "66a0efa41570ed494f18bd16",
    order: 18,
  },
  {
    adult: false,
    gender: 1,
    id: 230660,
    known_for_department: "Acting",
    name: "Shioli Kutsuna",
    original_name: "Shioli Kutsuna",
    popularity: 20.377,
    profile_path: "/5EdMbcRIemzLszjEr36Ic0Obmdb.jpg",
    cast_id: 264,
    character: "Yukio",
    credit_id: "66a0f0811570ed494f18bd26",
    order: 19,
  },
  {
    adult: false,
    gender: 2,
    id: 80507,
    known_for_department: "Acting",
    name: "Stefan Kapicic",
    original_name: "Stefan Kapicic",
    popularity: 14.121,
    profile_path: "/6qHO7ckiyjLNOmW0v5RZj1MpLBj.jpg",
    cast_id: 260,
    character: "Colossus (voice)",
    credit_id: "66a0eff7958531da34bf6286",
    order: 20,
  },
  {
    adult: false,
    gender: 2,
    id: 215887,
    known_for_department: "Acting",
    name: "Randal Reeder",
    original_name: "Randal Reeder",
    popularity: 13.875,
    profile_path: "/eJfW7w36Vl8dEnN9T2dnlkUReWG.jpg",
    cast_id: 279,
    character: "Buck",
    credit_id: "66a0f2536e2a098d255dad9b",
    order: 21,
  },
  {
    adult: false,
    gender: 2,
    id: 1610940,
    known_for_department: "Acting",
    name: "Lewis Tan",
    original_name: "Lewis Tan",
    popularity: 6.376,
    profile_path: "/ik347wakcZRfULiLbjGJpRcqSQz.jpg",
    cast_id: 262,
    character: "Shatterstar",
    credit_id: "66a0f0364f446414cf0bea38",
    order: 22,
  },
  {
    adult: false,
    gender: 2,
    id: 4561764,
    known_for_department: "Acting",
    name: "Nick Pauley",
    original_name: "Nick Pauley",
    popularity: 0.001,
    profile_path: "/9cJGBxmPiZ21C71DueJLDOuPc5c.jpg",
    cast_id: 301,
    character: "Dancepool",
    credit_id: "66a1f00aadc660b3fb265bf9",
    order: 23,
  },
  {
    adult: false,
    gender: 1,
    id: 963257,
    known_for_department: "Acting",
    name: "Sonita Henry",
    original_name: "Sonita Henry",
    popularity: 13.019,
    profile_path: "/oIBILFSVqHT2warKlXSPDML3llI.jpg",
    cast_id: 302,
    character: "Mrs. Chipman",
    credit_id: "66a1f015c7271d45f9cf8367",
    order: 24,
  },
  {
    adult: false,
    gender: 2,
    id: 1850835,
    known_for_department: "Acting",
    name: "Ryan McKen",
    original_name: "Ryan McKen",
    popularity: 4.159,
    profile_path: "/lGVReBLi74MCxaCBr2KBx1zTiWV.jpg",
    cast_id: 303,
    character: "Mr. Chipman",
    credit_id: "66a1f023a9212776c5e0fc39",
    order: 25,
  },
  {
    adult: false,
    gender: 0,
    id: 4848497,
    known_for_department: "Acting",
    name: "Nanak Phlora",
    original_name: "Nanak Phlora",
    popularity: 0.569,
    profile_path: null,
    cast_id: 304,
    character: "Elliot Chipman",
    credit_id: "66a1f035a830bd008f088731",
    order: 26,
  },
  {
    adult: false,
    gender: 0,
    id: 4848499,
    known_for_department: "Acting",
    name: "Aydin Ahmed",
    original_name: "Aydin Ahmed",
    popularity: 0.737,
    profile_path: null,
    cast_id: 305,
    character: "Kevin Chipman",
    credit_id: "66a1f063eb5b530b3acf829e",
    order: 27,
  },
  {
    adult: false,
    gender: 2,
    id: 1649401,
    known_for_department: "Acting",
    name: "Leemore Marrett Jr.",
    original_name: "Leemore Marrett Jr.",
    popularity: 4.242,
    profile_path: "/lrr8xbevZFfCMixuSPnUjwO2Oqa.jpg",
    cast_id: 306,
    character: "Minuteman Leader",
    credit_id: "66a1f075fd5d5c9bfedda32c",
    order: 28,
  },
  {
    adult: false,
    gender: 2,
    id: 1587576,
    known_for_department: "Acting",
    name: "James Dryden",
    original_name: "James Dryden",
    popularity: 7.495,
    profile_path: "/1Z3CjM13uhOlt6dUyHaewkBjUcO.jpg",
    cast_id: 307,
    character: "TVA Tech",
    credit_id: "66a1f086bcf6b96327f78c14",
    order: 29,
  },
  {
    adult: false,
    gender: 2,
    id: 4698632,
    known_for_department: "Acting",
    name: "Ollie Palmer",
    original_name: "Ollie Palmer",
    popularity: 0.638,
    profile_path: "/kICsR18nsLMjxMrIWjJKtOsAkJj.jpg",
    cast_id: 308,
    character: "Bar Patron",
    credit_id: "66a1f0a22b0919f669a0d0ba",
    order: 30,
  },
  {
    adult: false,
    gender: 2,
    id: 167008,
    known_for_department: "Acting",
    name: "Greg Hemphill",
    original_name: "Greg Hemphill",
    popularity: 5.014,
    profile_path: "/juE0ZmdUbxfMBhtOz9LBV8MiLKH.jpg",
    cast_id: 281,
    character: "Seedy Bartender",
    credit_id: "66a0f2914194f9b3d7dd7722",
    order: 31,
  },
  {
    adult: false,
    gender: 2,
    id: 3158217,
    known_for_department: "Acting",
    name: "Aaron W Reed",
    original_name: "Aaron W Reed",
    popularity: 26.898,
    profile_path: "/e9dW9ezNxeGEu8MnQ1NTOz3PM93.jpg",
    cast_id: 323,
    character: "Juggernaut",
    credit_id: "66a301b3073923ad4918fbc1",
    order: 32,
  },
  {
    adult: false,
    gender: 0,
    id: 4854075,
    known_for_department: "Acting",
    name: "Mike Waters",
    original_name: "Mike Waters",
    popularity: 0.451,
    profile_path: null,
    cast_id: 329,
    character: "Blob",
    credit_id: "66a6881cef66779c2a40bae8",
    order: 33,
  },
  {
    adult: false,
    gender: 2,
    id: 78597,
    known_for_department: "Acting",
    name: "Rob McElhenney",
    original_name: "Rob McElhenney",
    popularity: 13.574,
    profile_path: "/gcep3ItyxaZ3ljH1IS6Lfkm8IAs.jpg",
    cast_id: 330,
    character: "TVA Soldier",
    credit_id: "66a6886032810e2e630954ff",
    order: 34,
  },
  {
    adult: false,
    gender: 1,
    id: 4854086,
    known_for_department: "Acting",
    name: "James Reynolds",
    original_name: "James Reynolds",
    popularity: 0.433,
    profile_path: null,
    cast_id: 331,
    character: "Screaming Mutant (voice)",
    credit_id: "66a688dce1321cc4eb7463d4",
    order: 35,
  },
  {
    adult: false,
    gender: 2,
    id: 1364950,
    known_for_department: "Acting",
    name: "Ed Kear",
    original_name: "Ed Kear",
    popularity: 7.754,
    profile_path: "/jB1QY1DSN253bbtz51MHXEBj9O8.jpg",
    cast_id: 309,
    character: "Outpost Tech",
    credit_id: "66a1f0ddd9ec811948cf8314",
    order: 36,
  },
  {
    adult: false,
    gender: 2,
    id: 1951011,
    known_for_department: "Acting",
    name: "Paul G. Raymond",
    original_name: "Paul G. Raymond",
    popularity: 2.35,
    profile_path: "/28pPNcmHZuH4XM4eUHoFGZF6LGA.jpg",
    cast_id: 310,
    character: "TVA Office Agent",
    credit_id: "66a1f0e8e455b7e8af18e453",
    order: 37,
  },
  {
    adult: false,
    gender: 1,
    id: 59175,
    known_for_department: "Acting",
    name: "Blake Lively",
    original_name: "Blake Lively",
    popularity: 58.147,
    profile_path: "/rkGVjd6wImtgjOCi0IpeffdEWtb.jpg",
    cast_id: 313,
    character: "Ladypool (voice)",
    credit_id: "66a1f42ebffb534f84e0fe30",
    order: 38,
  },
  {
    adult: false,
    gender: 0,
    id: 4846410,
    known_for_department: "Acting",
    name: "Inez Reynolds",
    original_name: "Inez Reynolds",
    popularity: 0.545,
    profile_path: null,
    cast_id: 318,
    character: "Kidpool (voice)",
    credit_id: "66a30047f807a42be983c2e1",
    order: 39,
  },
  {
    adult: false,
    gender: 2,
    id: 51797,
    known_for_department: "Acting",
    name: "Nathan Fillion",
    original_name: "Nathan Fillion",
    popularity: 57.493,
    profile_path: "/aW6vCxkUZtwb6iH2Wf88Uq0XNVv.jpg",
    cast_id: 319,
    character: "Headpool (voice)",
    credit_id: "66a300706efb745b63d4f23e",
    order: 40,
  },
  {
    adult: false,
    gender: 2,
    id: 10297,
    known_for_department: "Acting",
    name: "Matthew McConaughey",
    original_name: "Matthew McConaughey",
    popularity: 36.372,
    profile_path: "/rUxLWWCDUF8RnDaocSqrVDJ2MS1.jpg",
    cast_id: 314,
    character: "Cowboypool (voice)",
    credit_id: "66a201662f9da16572383f13",
    order: 41,
  },
  {
    adult: false,
    gender: 0,
    id: 4850040,
    known_for_department: "Acting",
    name: "OIin Reynolds",
    original_name: "OIin Reynolds",
    popularity: 0.586,
    profile_path: null,
    cast_id: 320,
    character: "Babypool (voice)",
    credit_id: "66a300856056ca7331cf98a2",
    order: 42,
  },
  {
    adult: false,
    gender: 0,
    id: 4338091,
    known_for_department: "Acting",
    name: "Paul Mullin",
    original_name: "Paul Mullin",
    popularity: 0.698,
    profile_path: "/bZZ4wvdMJtt6aPUSQAAY4G7mzbe.jpg",
    cast_id: 321,
    character: "Welshpool",
    credit_id: "66a30099f410fb5dd314f3ab",
    order: 43,
  },
  {
    adult: false,
    gender: 2,
    id: 2280082,
    known_for_department: "Crew",
    name: "Alex Kyshkovych",
    original_name: "Alex Kyshkovych",
    popularity: 3.812,
    profile_path: "/nyy5o659Z1LfLl9ckRT1FiNop4U.jpg",
    cast_id: 322,
    character: "Canadapool",
    credit_id: "66a300a949a40fe7d55d46de",
    order: 44,
  },
  {
    adult: false,
    gender: 2,
    id: 74568,
    known_for_department: "Acting",
    name: "Chris Hemsworth",
    original_name: "Chris Hemsworth",
    popularity: 44.108,
    profile_path: "/piQGdoIQOF3C1EI5cbYZLAW1gfj.jpg",
    cast_id: 333,
    character: "Thor Odinson (archive footage) (uncredited)",
    credit_id: "66a7ee63db5ac8177656c57b",
    order: 45,
  },
  {
    adult: false,
    gender: 2,
    id: 2423284,
    known_for_department: "Crew",
    name: "Billy Clements",
    original_name: "Billy Clements",
    popularity: 2.947,
    profile_path: "/nipJ22DXJBsdM1teQodwop42U6S.jpg",
    cast_id: 332,
    character: "Russian (uncredited)",
    credit_id: "66a6899a1156084b5fdaf78d",
    order: 46,
  },
  {
    adult: false,
    gender: 2,
    id: 4857614,
    known_for_department: "Acting",
    name: "Daniel Medina Ramos",
    original_name: "Daniel Medina Ramos",
    popularity: 1.045,
    profile_path: "/3ZmlKGTlBF09ZxmoOH9lB1xdsf2.jpg",
    cast_id: 335,
    character: "Toad (uncredited)",
    credit_id: "66a8ff8cb47e5a4ccdebc6c0",
    order: 47,
  },
  {
    adult: false,
    gender: 1,
    id: 4115448,
    known_for_department: "Crew",
    name: "Jade Lye",
    original_name: "Jade Lye",
    popularity: 23.138,
    profile_path: "/4r1zrh8Wf32W74fltUn37Uz2FfV.jpg",
    cast_id: 337,
    character: "Lady Deathstrike (uncredited)",
    credit_id: "66a96e46f9c9f9f3a4e3aca7",
    order: 48,
  },
  {
    adult: false,
    gender: 0,
    id: 4858600,
    known_for_department: "Crew",
    name: "Nilly Cetin",
    original_name: "Nilly Cetin",
    popularity: 1.667,
    profile_path: "/vLKWIjSztXEHUOMFolVudij4jbs.jpg",
    cast_id: 339,
    character: "Quill (uncredited)",
    credit_id: "66a97034b2bfdd9e37837c54",
    order: 49,
  },
  {
    adult: false,
    gender: 2,
    id: 2423287,
    known_for_department: "Crew",
    name: "Eduardo Gago Muñoz",
    original_name: "Eduardo Gago Muñoz",
    popularity: 1.677,
    profile_path: "/r9DaaOfiACoUX7Ezs63K8DZrpHI.jpg",
    cast_id: 341,
    character: "Azazel (uncredited)",
    credit_id: "66a971ad9f6dabe412bfccf3",
    order: 50,
  },
  {
    adult: false,
    gender: 0,
    id: 4858628,
    known_for_department: "Crew",
    name: "Chloe Kibble",
    original_name: "Chloe Kibble",
    popularity: 0.707,
    profile_path: "/6jgp3IJenhe9R1cdV25gfzlSDpy.jpg",
    cast_id: 344,
    character: "Callisto (uncredited)",
    credit_id: "66a9757cdca616e20759c86c",
    order: 51,
  },
  {
    adult: false,
    gender: 0,
    id: 2151833,
    known_for_department: "Crew",
    name: "Curtis Rowland Small",
    original_name: "Curtis Rowland Small",
    popularity: 3.663,
    profile_path: "/lgAOeihmiZ2CdKWpa35BxpBeSiK.jpg",
    cast_id: 346,
    character: "Bullseye (uncredited)",
    credit_id: "66a9773bfd1353a12e837c7e",
    order: 52,
  },
  {
    adult: false,
    gender: 1,
    id: 4733517,
    known_for_department: "Crew",
    name: "Ayesha Hussain",
    original_name: "Ayesha Hussain",
    popularity: 0.001,
    profile_path: "/7bChdeG2k7GoAf8nG12p05Ssrbe.jpg",
    cast_id: 347,
    character: "Psylocke (uncredited)",
    credit_id: "66a9789265780b6119cd19ed",
    order: 53,
  },
  {
    adult: false,
    gender: 0,
    id: 4858668,
    known_for_department: "Crew",
    name: "Jessica Walker",
    original_name: "Jessica Walker",
    popularity: 1.54,
    profile_path: "/5fZ41rVpPKI5VpBFt2dBRcOaHtL.jpg",
    cast_id: 349,
    character: "Arclight (uncredited)",
    credit_id: "66a979ebb2bfdd9e37837c98",
    order: 54,
  },
  {
    adult: false,
    gender: 2,
    id: 1674196,
    known_for_department: "Acting",
    name: "Harry Holland",
    original_name: "Harry Holland",
    popularity: 15.281,
    profile_path: "/8gsfzGUySLLaT0GCzuWxAfLWOWS.jpg",
    cast_id: 334,
    character: "Haroldpool (uncredited)",
    credit_id: "66a806f50fb65ccb569fd9ee",
    order: 55,
  },
  {
    adult: false,
    gender: 2,
    id: 3411282,
    known_for_department: "Crew",
    name: "Kevin Fortin",
    original_name: "Kevin Fortin",
    popularity: 0.713,
    profile_path: "/bRBUOhX9Oc0A2nNARsP4jkoDzva.jpg",
    cast_id: 350,
    character: "Zenpool (uncredited)",
    credit_id: "66ade5ed089fe1f033c05828",
    order: 56,
  },
];
